### ISSUE TITLE
parser V2 fixes/improvements

### ISSUE THREAD

**Issue by sl16** [sl16/42-cub3d#11]
// add 'open' checks to texture to check if files actually exist?
// ERR_MISSING_VALUE checker for colours needs better condition (what if specified colors == 0?)
// add further parsing checks for values

**Comment by andreaulicna** [comment]
Parser throws a "The map's perimeter is not enclosed in walls." or "The map's inner spaces must be enclosed."  for a valid map that is separated by more than one line from the rest of the map file and the separation lines contain (some) spaces -> it behaves weird, a couple of spaces seems to be okay, but if they are across the whole line it isn't, hence 'some'.

[validmap3.txt](https://github.com/sl16/42-cub3d/files/14530382/validmap3.txt)


[map_square.txt](https://github.com/sl16/42-cub3d/files/14530388/map_square.txt)
